### ISSUE TITLE
npm build hangs

### ISSUE THREAD

**Issue by robksawyer** [DBosley/keystone-angular2-webpack-starter#2]
Build is hanging on the following. Any ideas? Below is what I get when I run `npm build`.

```
$ node_modules/.bin/rimraf dist && node_modules/.bin/webpack --progress --profile --bail
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
758ms building modules
3ms sealing
0ms optimizing
0ms basic module optimization
1ms module optimization
0ms advanced module optimization
3ms basic chunk optimization
0ms chunk optimization
1ms advanced chunk optimization
0ms module and chunk tree optimization
3ms module reviving
1ms module order optimization
2ms module id optimization
2ms chunk reviving
1ms chunk order optimization
3ms chunk id optimization
4ms hashing
1ms module assets processing
85ms chunk assets processing
2ms additional chunk assets processing
0ms recording
0ms additional asset processing
2ms chunk asset optimization
15ms asset optimization
7ms emitting
Hash: 6869ffb022f75b7b2f4b
Version: webpack 2.4.1
Time: 919ms
          Asset       Size  Chunks             Chunk Names
      js/app.js     197 kB       0  [emitted]  app
   js/vendor.js  494 bytes       1  [emitted]  vendor
js/polyfills.js    30.9 kB       2  [emitted]  polyfills
     index.html    4.17 kB          [emitted]
   [0] ./~/html-entities/lib/html5-entities.js 49 kB {0} [built]
       [] -> factory:7ms building:94ms = 101ms
   [1] ./src/main.ts 226 bytes {0} [built] [failed] [1 error]
       [] -> factory:322ms building:62ms = 384ms
   [2] (webpack)-hot-middleware/client.js 6.68 kB {0} [built]
       [] -> factory:68ms building:299ms = 367ms
   [3] ./~/ansi-html/index.js 4.26 kB {0} [built]
       [] -> factory:37ms building:30ms = 67ms
   [4] ./~/ansi-regex/index.js 135 bytes {0} [built]
       [] -> factory:26ms building:28ms = 54ms
   [5] ./src/polyfills.ts 226 bytes {2} [built] [failed] [1 error]
        factory:95ms building:291ms = 386ms
   [6] ./src/vendor.ts 226 bytes {1} [built] [failed] [1 error]
        factory:324ms building:60ms = 384ms
   [7] ./~/html-entities/index.js 231 bytes {0} [built]
       [] -> factory:40ms building:28ms = 68ms
   [8] ./~/html-entities/lib/html4-entities.js 6.57 kB {0} [built]
       [] -> factory:6ms building:31ms = 37ms
   [9] ./~/html-entities/lib/xml-entities.js 2.98 kB {0} [built]
       [] -> factory:5ms building:37ms = 42ms
  [10] ./~/strip-ansi/index.js 161 bytes {0} [built]
       [] -> factory:237ms building:2ms = 239ms
  [11] (webpack)-hot-middleware/client-overlay.js 1.82 kB {0} [built]
       [] -> factory:6ms building:214ms = 220ms
  [12] (webpack)-hot-middleware/process-update.js 3.88 kB {0} [built]
       [] -> factory:6ms building:228ms = 234ms
  [13] (webpack)/buildin/module.js 517 bytes {0} [built]
       [] -> factory:236ms building:13ms = 249ms
  [14] multi ./src/main.ts webpack-hot-middleware/client 40 bytes {0} [built]
        factory:0ms building:2ms = 2ms

ERROR in ./src/vendor.ts
Module build failed: TypeError: Can't add property fileName, object is not extensible
    at Object.Linter (/Users/robsawyer/Sites/keystone-angular2-webpack-starter/node_modules/tslint/lib/tslint.js:12:23)

ERROR in ./src/polyfills.ts
Module build failed: TypeError: Can't add property fileName, object is not extensible
    at Object.Linter (/Users/robsawyer/Sites/keystone-angular2-webpack-starter/node_modules/tslint/lib/tslint.js:12:23)

ERROR in ./src/main.ts
Module build failed: TypeError: Can't add property fileName, object is not extensible
    at Object.Linter (/Users/robsawyer/Sites/keystone-angular2-webpack-starter/node_modules/tslint/lib/tslint.js:12:23)
 @ multi ./src/main.ts webpack-hot-middleware/client

ERROR in   EntryModuleNotFoundError: Entry module not found: Error: Can't resolve 'raw' in '/Users/robsawyer/Sites/keystone-angular2-webpack-starter'
  BREAKING CHANGE: It's no longer allowed to omit the '-loader' suffix when using loaders.
                   You need to specify 'raw-loader' instead of 'raw',
                   see https://webpack.js.org/guides/migrating/#automatic-loader-module-name-extension-removed

  - Compilation.js:387
    [keystone-angular2-webpack-starter]/[webpack]/lib/Compilation.js:387:29

  - NormalModuleFactory.js:247
    [keystone-angular2-webpack-starter]/[webpack]/lib/NormalModuleFactory.js:247:20

  - NormalModuleFactory.js:65
    [keystone-angular2-webpack-starter]/[webpack]/lib/NormalModuleFactory.js:65:21

  - NormalModuleFactory.js:202
    [keystone-angular2-webpack-starter]/[webpack]/lib/NormalModuleFactory.js:202:22

  - async.js:3824
    [keystone-angular2-webpack-starter]/[webpack]/[async]/dist/async.js:3824:9

  - async.js:460
    [keystone-angular2-webpack-starter]/[webpack]/[async]/dist/async.js:460:16

  - async.js:1032 iteratorCallback
    [keystone-angular2-webpack-starter]/[webpack]/[async]/dist/async.js:1032:13

  - async.js:944
    [keystone-angular2-webpack-starter]/[webpack]/[async]/dist/async.js:944:16

  - async.js:3821
    [keystone-angular2-webpack-starter]/[webpack]/[async]/dist/async.js:3821:13

  - async.js:21 apply
    [keystone-angular2-webpack-starter]/[webpack]/[async]/dist/async.js:21:25

  - async.js:56
    [keystone-angular2-webpack-starter]/[webpack]/[async]/dist/async.js:56:12

  - async.js:1110
    [keystone-angular2-webpack-starter]/[webpack]/[async]/dist/async.js:1110:9

  - async.js:460
    [keystone-angular2-webpack-starter]/[webpack]/[async]/dist/async.js:460:16

  - async.js:1032 iteratorCallback
    [keystone-angular2-webpack-starter]/[webpack]/[async]/dist/async.js:1032:13

  - async.js:944
    [keystone-angular2-webpack-starter]/[webpack]/[async]/dist/async.js:944:16

  - async.js:1107
    [keystone-angular2-webpack-starter]/[webpack]/[async]/dist/async.js:1107:13

  - NormalModuleFactory.js:270
    [keystone-angular2-webpack-starter]/[webpack]/lib/NormalModuleFactory.js:270:7

  - Resolver.js:72 onResolved
    [keystone-angular2-webpack-starter]/[webpack]/[enhanced-resolve]/lib/Resolver.js:72:10

  - createInnerCallback.js:31 loggingCallbackWrapper
    [keystone-angular2-webpack-starter]/[webpack]/[enhanced-resolve]/lib/createInnerCallback.js:31:19

  - Resolver.js:122 innerCallback
    [keystone-angular2-webpack-starter]/[webpack]/[enhanced-resolve]/lib/Resolver.js:122:22

  - createInnerCallback.js:31 loggingCallbackWrapper
    [keystone-angular2-webpack-starter]/[webpack]/[enhanced-resolve]/lib/createInnerCallback.js:31:19

  - Tapable.js:283
    [keystone-angular2-webpack-starter]/[tapable]/lib/Tapable.js:283:15

  - UnsafeCachePlugin.js:37
    [keystone-angular2-webpack-starter]/[webpack]/[enhanced-resolve]/lib/UnsafeCachePlugin.js:37:22

  - createInnerCallback.js:31 loggingCallbackWrapper
    [keystone-angular2-webpack-starter]/[webpack]/[enhanced-resolve]/lib/createInnerCallback.js:31:19

  - Resolver.js:122 innerCallback
    [keystone-angular2-webpack-starter]/[webpack]/[enhanced-resolve]/lib/Resolver.js:122:22

  - createInnerCallback.js:31 loggingCallbackWrapper
    [keystone-angular2-webpack-starter]/[webpack]/[enhanced-resolve]/lib/createInnerCallback.js:31:19

  - Tapable.js:283
    [keystone-angular2-webpack-starter]/[tapable]/lib/Tapable.js:283:15

  - Resolver.js:122 innerCallback
    [keystone-angular2-webpack-starter]/[webpack]/[enhanced-resolve]/lib/Resolver.js:122:22

  - createInnerCallback.js:31 loggingCallbackWrapper
    [keystone-angular2-webpack-starter]/[webpack]/[enhanced-resolve]/lib/createInnerCallback.js:31:19

  - Tapable.js:283
    [keystone-angular2-webpack-starter]/[tapable]/lib/Tapable.js:283:15

```

**Comment by DBosley** [comment]
Sorry for the slow reply, this repo was very experimental, I never quite
got it all working and it's now terribly out of date. I plan to pick it
back up soon, but right now it's probably best to look elsewhere for a
keystone and angular solution.
